### ISSUE TITLE
irtest - which controller did you use?

### ISSUE THREAD

**Issue by Yariv-h** [atuline/FastLED-Demos#27]
Hi,

I was looking around and i saw the more ppl had the same issue as i - Arduino interrupts are collided with the IR remote  - did you used teensy here? or you has a successful run with Arduino?

**Comment by Yariv-h** [comment]
irtest:56: error: 'IR_NEC' was not declared in this scope

   attachInterrupt(digitalPinToInterrupt(pinIR), IRLinterrupt<IR_NEC>, CHANGE);    // IR definition

                                                              ^

irtest:56: error: expected primary-expression before ',' token

   attachInterrupt(digitalPinToInterrupt(pinIR), IRLinterrupt<IR_NEC>, CHANGE);    // IR definition

**Comment by atuline** [comment]
Looks like he's changed his API (again), so I'll be updating my codebase to suit. In the meantime, I was testing on Nano with TSOP32838 and am now just getting into ESP8266's.

The line I'll be adding right after the pin definition is:

CNec IRLremote;

**Comment by Yariv-h** [comment]
Hi - could you confirm that you successfully integrate the IR Remote with the FastLED lib using Arduino? If so - which one did you use? I'm trying to make it work with Arduino UNO & Micro Pro without any success .. according to Reddit it impossible do to the interrupts issue - but i don't need fully supported solution, just something that would change the effect even after few tries is fine...

**Comment by atuline** [comment]
Not IR Remote, but IRLRemote by Nico Hood. Two different libraries.

I developed all my routines on an Arduino Nano, and in order to use IRLRemote and FastLED on a Nano, you need to use 4 pin LED strips such as APA102's. As you mentioned, this is due to the interrupt issue.

Also, like I said, the author of IRLRemote appears to have changed his API a bit, so I'll need to update my codebase, which was all developed on Nano's. His examples should work just fine and it should be pretty easy to tack on a basic FastLED test program.

I also just tested the latest version of IRLRemote on a WeMOS D1 Mini (ESP8266) and got that running with FastLED and some WS2812's. The IR responded as expected about 75% of the time, so it might take a couple of button presses on occasion. I used pin D2 for the IR and D5 for the WS2812's.

**Comment by Yariv-h** [comment]
> Not IR Remote, but IRLRemote by Nico Hood. Two different libraries.
> 
> I developed all my routines on an Arduino Nano, and in order to use IRLRemote and FastLED on a Nano, you need to use 4 pin LED strips such as APA102's. As you mentioned, this is due to the interrupt issue.
> 
> Also, like I said, the author of IRLRemote appears to have changed his API a bit, so I'll need to update my codebase, which was all developed on Nano's. His examples should work just fine and it should be pretty easy to tack on a basic FastLED test program.
> 
> I also just tested the latest version of IRLRemote on a WeMOS D1 Mini (ESP8266) and got that running with FastLED and some WS2812's. The IR responded as expected about 75% of the time, so it might take a couple of button presses on occasion. I used pin D2 for the IR and D5 for the WS2812's.

Got you, will give it a try! 10x! :)

**Comment by atuline** [comment]
Good luck! Don't forget to hang out on https://www.reddit.com/r/fastled
