### ISSUE TITLE
Slow FPS

### ISSUE THREAD

**Issue by crashza** [atuline/FastLED-Demos#30]
Hi Andrew, 
Firstly great work on these effects.
This is more of a question so here it is.
 
I am using your soundmems code in a project of mine and its working flawlessly on a small strip of leds 40 ws2812s (Code is on a esp8266) I get a steady FPS of 400 with this config, When i increase the LED count to 680 I get a low FPS around 10 or so and the animations dont work as they should, Is this very low FPS expected when running so many LED's?

Regards
Trevor

**Comment by atuline** [comment]
Hi Trevor,

 

Yes, the animation is very slow on a larger amount of LED’s using WS2812’s, which is why a lot of people revert to parallel outputs or use APA102’s, which have a much higher data rate.

 

In general, parallel output with WS2812’s seems to be the way most people get around that.

 

As for calculations, here’s something I just dug up:

 

The datarate should be 400 KHz or 800 KHz (FastLed,h library).
Each WS2812B needs 24 bits of data.
Thus at 800 KHz/24 bits/LED, you can send 33,333 LEDs worth of data in one second.
If you want to update at a 50 Hz rate, then you get 1/50 of that, so 666 LEDs.
100 Levels = 6 LEDs per level.  If 400K, then just 3.
"The display rotates at 3000 RPM = 50Hz"  3000 rev/minute * 1 minute/60 seconds = 50 revs/sec, or 50 Hz. Ok.

 

Note that the above is the ‘theoretical’ maximum you could possibly get, not counting the overhead of any ESP8266 processing.

 

 

Hope that helps,

 

 

Andrew

**Comment by crashza** [comment]
Thanks Andrew, I will give that a go thanks for responding
